plugins {
    id 'fabric-loom' version '1.4-SNAPSHOT'
    id 'maven-publish'
}
version = '0.1.0-beta'
group = 'com.floppyfish'
repositories {}
loom { splitEnvironmentSourceSets() }
dependencies {
    minecraft 'com.mojang:minecraft:1.20.1'
    mappings 'net.fabricmc:yarn:1.20.1+build.10:v2'
    modImplementation 'net.fabricmc:fabric-loader:0.14.22'
    modImplementation 'net.fabricmc.fabric-api:fabric-api:0.92.0+1.20.1'
}
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 17
}
java { withSourcesJar() }
